2025-03-05 09:07:02,284 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:07:02,284 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Configure stats pid to 17636
2025-03-05 09:07:02,284 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:07:02,284 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:07:02,284 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:07:02,284 INFO    MainThread:17636 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_090702-avgldy14\logs\debug.log
2025-03-05 09:07:02,285 INFO    MainThread:17636 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_090702-avgldy14\logs\debug-internal.log
2025-03-05 09:07:02,285 INFO    MainThread:17636 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001DAD3248110>
2025-03-05 09:07:02,285 INFO    MainThread:17636 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:07:02,285 INFO    MainThread:17636 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-05 09:07:02,285 INFO    MainThread:17636 [wandb_init.py:init():784] starting backend
2025-03-05 09:07:02,285 INFO    MainThread:17636 [wandb_init.py:init():788] sending inform_init request
2025-03-05 09:07:02,286 INFO    MainThread:17636 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-05 09:07:02,287 INFO    MainThread:17636 [wandb_init.py:init():803] backend started and connected
2025-03-05 09:07:02,290 INFO    MainThread:17636 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-05 09:07:02,301 INFO    MainThread:17636 [wandb_init.py:init():896] updated telemetry
2025-03-05 09:07:02,346 INFO    MainThread:17636 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 09:07:04,006 INFO    MainThread:17636 [wandb_init.py:init():995] starting run threads in backend
2025-03-05 09:07:04,327 INFO    MainThread:17636 [wandb_run.py:_console_start():2377] atexit reg
2025-03-05 09:07:04,327 INFO    MainThread:17636 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-05 09:07:04,327 INFO    MainThread:17636 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-05 09:07:04,327 INFO    MainThread:17636 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-05 09:07:04,328 INFO    MainThread:17636 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-05 09:07:05,126 INFO    MainThread:17636 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 09:07:05,126 INFO    MainThread:17636 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 09:07:07,058 INFO    MainThread:17636 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 09:07:07,062 INFO    MainThread:17636 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=None
2025-03-05 09:07:08,013 WARNING MsgRouterThr:17636 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 09:07:08,048 INFO    MsgRouterThr:17636 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-05 09:07:09,759 INFO    Thread-753 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:07:13,437 INFO    Thread-754 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:07:23,472 INFO    Thread-755 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:07:24,425 INFO    Thread-756 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:07:34,465 INFO    Thread-757 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:07:35,282 INFO    Thread-758 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:07:45,358 INFO    Thread-759 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:07:46,082 INFO    Thread-760 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:07:56,122 INFO    Thread-761 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:07:56,887 INFO    Thread-762 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:06,930 INFO    Thread-763 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:07,791 INFO    Thread-764 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:17,822 INFO    Thread-765 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:18,702 INFO    Thread-766 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:28,735 INFO    Thread-767 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:29,716 INFO    Thread-768 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:39,757 INFO    Thread-769 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:40,485 INFO    Thread-770 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:50,525 INFO    Thread-771 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:08:51,477 INFO    Thread-772 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:09:01,509 INFO    Thread-773 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:09:02,466 INFO    Thread-774 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:09:12,508 INFO    Thread-775 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:09:13,559 INFO    Thread-776 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:09:23,603 INFO    Thread-777 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:09:24,631 INFO    Thread-778 (_run_job):17636 [wandb_run.py:_finish():2112] finishing run da24m014-iit-madras/Assignment - 1/avgldy14
2025-03-05 09:09:29,659 INFO    MainThread:17636 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 09:09:29,659 INFO    MainThread:17636 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 09:09:31,082 INFO    MainThread:17636 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 09:09:31,787 INFO    MainThread:17636 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 09:09:31,787 INFO    MainThread:17636 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 09:09:45,376 INFO    MainThread:17636 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 09:09:46,019 INFO    MainThread:17636 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 09:09:46,019 INFO    MainThread:17636 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 09:10:01,843 INFO    MainThread:17636 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 09:10:01,946 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 09:10:01,946 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Configure stats pid to 17636
2025-03-05 09:10:01,946 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Rajat\.config\wandb\settings
2025-03-05 09:10:01,946 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Loading settings from d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\settings
2025-03-05 09:10:01,946 INFO    MainThread:17636 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 09:10:01,946 INFO    MainThread:17636 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091001-crnz1x7e\logs\debug.log
2025-03-05 09:10:01,947 INFO    MainThread:17636 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091001-crnz1x7e\logs\debug-internal.log
2025-03-05 09:10:01,947 INFO    MainThread:17636 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:10:01,947 INFO    MainThread:17636 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-05 09:10:01,947 INFO    MainThread:17636 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:10:01,947 ERROR   MainThread:17636 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:10:02,469 INFO    MainThread:17636 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 09:10:02,469 INFO    MainThread:17636 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 09:10:08,850 INFO    MainThread:17636 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 09:10:08,895 INFO    MainThread:17636 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 09:10:08,895 INFO    MainThread:17636 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 09:10:10,377 INFO    MainThread:17636 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 09:10:10,445 INFO    MainThread:17636 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091010-37bktzur\logs\debug.log
2025-03-05 09:10:10,445 INFO    MainThread:17636 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091010-37bktzur\logs\debug-internal.log
2025-03-05 09:10:10,446 INFO    MainThread:17636 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:10:10,446 INFO    MainThread:17636 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-05 09:10:10,446 INFO    MainThread:17636 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:10:10,451 ERROR   MainThread:17636 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:10:10,601 INFO    MainThread:17636 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 09:10:10,601 INFO    MainThread:17636 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-05 09:10:44,651 INFO    MainThread:17636 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-05 09:10:44,724 INFO    MainThread:17636 [wandb_init.py:setup_run_log_directory():647] Logging user logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091044-5735ktpj\logs\debug.log
2025-03-05 09:10:44,724 INFO    MainThread:17636 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to d:\IIT Madras\SEM 2\Deep Learning\Assignment-1-DL\wandb\run-20250305_091044-5735ktpj\logs\debug-internal.log
2025-03-05 09:10:44,724 INFO    MainThread:17636 [wandb_init.py:init():761] calling init triggers
2025-03-05 09:10:44,725 INFO    MainThread:17636 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-05 09:10:44,725 INFO    MainThread:17636 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-05 09:10:44,727 ERROR   MainThread:17636 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\Rajat\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-05 09:10:44,853 INFO    MainThread:17636 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-05 09:10:44,853 INFO    MainThread:17636 [wandb_init.py:_pause_backend():564] pausing backend
